spring:
  datasource:
    url: jdbc:postgresql://postgres-order:5432/orderdb
    username: order
    password: order

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

