# =========================
# Basic
# =========================
bind 0.0.0.0
port 6379
protected-mode no

# =========================
# Memory management
# =========================
# Giới hạn RAM (rất quan trọng)
maxmemory 512mb

# Chính sách eviction:
# allkeys-lru: cache + cart + rate-limit rất hợp
maxmemory-policy allkeys-lru

# =========================
# Persistence
# =========================
# Snapshot RDB
save 900 1
save 300 10
save 60 10000

dir /data
dbfilename dump.rdb

# AOF (append only) - OFF cho local dev
appendonly no

# =========================
# Performance
# =========================
tcp-keepalive 300
timeout 0

# =========================
# Logging
# =========================
loglevel notice
logfile ""

# =========================
# Safety
# =========================
# Không cho flushall nếu cần an toàn hơn
# rename-command FLUSHALL ""
# rename-command FLUSHDB ""
